DROP TRIGGER IF EXISTS update_member_count_trigger ON community_members;
DROP TRIGGER IF EXISTS update_webhooks_updated_at ON webhooks;
DROP TRIGGER IF EXISTS update_custom_emojis_updated_at ON custom_emojis;
DROP TRIGGER IF EXISTS update_user_settings_updated_at ON user_settings;
DROP TRIGGER IF EXISTS update_dm_conversations_updated_at ON dm_conversations;
DROP TRIGGER IF EXISTS update_roles_updated_at ON roles;
DROP TRIGGER IF EXISTS update_channels_updated_at ON channels;
DROP TRIGGER IF EXISTS update_communities_updated_at ON communities;
DROP TRIGGER IF EXISTS update_users_updated_at ON users;

DROP FUNCTION IF EXISTS update_community_member_count();
DROP FUNCTION IF EXISTS update_updated_at_column();

DROP TABLE IF EXISTS channel_read_states;
DROP TABLE IF EXISTS webhooks;
DROP TABLE IF EXISTS user_friendships;
DROP TABLE IF EXISTS friend_requests;
DROP TABLE IF EXISTS plugin_audit_log;
DROP TABLE IF EXISTS plugin_sources;
DROP TABLE IF EXISTS community_plugins;
DROP TABLE IF EXISTS plugins;
DROP TABLE IF EXISTS community_bans;
DROP TABLE IF EXISTS custom_emojis;
DROP TABLE IF EXISTS voice_states;
DROP TABLE IF EXISTS message_mentions;
DROP TABLE IF EXISTS notifications;
DROP TABLE IF EXISTS audit_logs;
DROP TABLE IF EXISTS user_settings;
DROP TABLE IF EXISTS user_blocks;
DROP TABLE IF EXISTS direct_messages;
DROP TABLE IF EXISTS dm_participants;
DROP TABLE IF EXISTS dm_conversations;
DROP TABLE IF EXISTS message_attachments;
DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS channel_permissions;
DROP TABLE IF EXISTS channel_type_definitions;
DROP TABLE IF EXISTS channels;
DROP TABLE IF EXISTS channel_categories;
DROP TABLE IF EXISTS member_roles;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS community_invites;
DROP TABLE IF EXISTS community_members;
DROP TABLE IF EXISTS communities;
DROP TABLE IF EXISTS user_sessions;
DROP TABLE IF EXISTS users;

DROP TYPE IF EXISTS channel_type;
DROP TYPE IF EXISTS user_status;
